services:
  xme-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/xme-backend:main
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/Xandme/data
      - uploads:/home/Xandme/uploads
      - ./config.toml:/home/Xandme/config.toml
      - type: bind
        source: ./documentation
        target: /home/Xandme/documentation
        read_only: true
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - xme-network
    restart: unless-stopped
    depends_on:
      - redis

  xme-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    depends_on:
      - xme-backend
    ports:
      - 3000:3000
    networks:
      - xme-network
    restart: unless-stopped
    
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - xme-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  xme-network:

volumes:
  backend-dbstore:
  uploads:
  redis-data:
