services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - xme-network
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    environment:
      - ALLOW_RESET=true
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - xme-network
    restart: unless-stopped

  xme-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/xme-backend:main
    environment:
      - SUPABASE_URL=
      - SUPABASE_KEY=
      - SEARXNG_API_URL=http://searxng:8080
      - DATABASE_URL=
    depends_on:
      - searxng
      - chroma
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/xme/data
      - uploads:/home/xme/uploads
      - ./config.toml:/home/perplexica/config.toml
      - type: bind
        source: ./documentation
        target: /home/xme/documentation
        read_only: true
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - xme-network
    restart: unless-stopped

  xme-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        NEXT_PUBLIC_WS_URL: ws://localhost:3001
        NEXT_PUBLIC_API_URL: http://localhost:3001/api
        NEXT_PUBLIC_SUPABASE_URL: https://qytbxgzxsywnfhlwcyqa.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY:
    environment:
      - NODE_ENV=production
      - STRIPE_SECRET_KEY=
      - STRIPE_WEBHOOK_SECRET=
      - SUPABASE_SERVICE_ROLE_KEY=
    depends_on:
      - xme-backend
    ports:
      - 3000:3000
    networks:
      - xme-network
    restart: unless-stopped

networks:
  xme-network:

volumes:
  backend-dbstore:
  uploads:
  chroma_data:
