services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - xme-network
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    environment:
      - ALLOW_RESET=true
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - xme-network
    restart: unless-stopped

  xme-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/xme-backend:main
    environment:
      - SUPABASE_URL=https://qytbxgzxsywnfhlwcyqa.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5dGJ4Z3p4c3l3bmZobHdjeXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEwNTc3MTAsImV4cCI6MjA0NjYzMzcxMH0.XLRq-4CFL2MWxvCLzCv5ZdaF5VSi58cocx9FOyv37jU
      - SEARXNG_API_URL=http://searxng:8080
      - DATABASE_URL=postgresql://postgres.ineclpmaolnshsnekjad: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@aws-0-us-east-1.pooler.supabase.com:6543/postgres
    depends_on:
      - searxng
      - chroma
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/xme/data
      - uploads:/home/xme/uploads
      - ./config.toml:/home/perplexica/config.toml
      - type: bind
        source: ./documentation
        target: /home/xme/documentation
        read_only: true
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - xme-network
    restart: unless-stopped

  xme-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        NEXT_PUBLIC_WS_URL: ws://localhost:3001
        NEXT_PUBLIC_API_URL: http://localhost:3001/api
        NEXT_PUBLIC_SUPABASE_URL: https://qytbxgzxsywnfhlwcyqa.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5dGJ4Z3p4c3l3bmZobHdjeXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEwNTc3MTAsImV4cCI6MjA0NjYzMzcxMH0.XLRq-4CFL2MWxvCLzCv5ZdaF5VSi58cocx9FOyv37jU
    environment:
      - NODE_ENV=production
      - STRIPE_SECRET_KEY=sk_test_51QqFgrHFhbg7l1ZnpMrvO6msUXRxrXJaQrcz0Zx90eMO3OjCNxzaR1TGPvN6wYUbH2nUMfbkURGO1RD5Py6Xodky00UV9J1PUe
      - STRIPE_WEBHOOK_SECRET=whsec_b0b30074b617ffe2d4f235e3101f55b7a870d1c17ebffdd7d1989d2ab59d646a
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5dGJ4Z3p4c3l3bmZobHdjeXFhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMTA1NzcxMCwiZXhwIjoyMDQ2NjMzNzEwfQ.xIB0Kyrsdv1q7yVde9rdROW0MBnRBT769hxyxsqa9n0
    depends_on:
      - xme-backend
    ports:
      - 3000:3000
    networks:
      - xme-network
    restart: unless-stopped

networks:
  xme-network:

volumes:
  backend-dbstore:
  uploads:
  chroma_data:
